In [1]:
import dgl
import torch

[Using backend: pytorch
09:55:40] /tmp/dgl_src/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: dlopen(/Users/yangbichen/opt/anaconda3/envs/pytorch1.9/lib/python3.8/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.11.0.dylib, 0x0001): tried: '/Users/yangbichen/opt/anaconda3/envs/pytorch1.9/lib/python3.8/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.11.0.dylib' (no such file)


In [7]:
g=dgl.data.CoraFull()[0]

/Users/yangbichen/opt/anaconda3/envs/pytorch1.9/lib/python3.8/site-packages/dgl/data/utils.py:294: UserWarning: Class CoraFull will be deprecated, please use CoraFullDataset instead.
  warnings.warn('Class {} will be deprecated, please use {} instead.'.format(old, new))


In [20]:
degree = g.in_degrees().float()
norm = torch.pow(degree,-0.5)
norm[torch.isinf(norm)]=0 

g.ndata['norm']=norm.unsqueeze(1)

In [21]:
feat=  g.ndata['feat']
weight = torch.Tensor(feat.shape[1],10)
g.ndata['h']=torch.mm(feat,weight)

In [22]:
g.ndata['h'].shape

torch.Size([19793, 10])

In [23]:
g.ndata['norm'].shape

torch.Size([19793, 1])

In [24]:
(g.ndata['h']*g.ndata['norm']).shape

torch.Size([19793, 10])

In [27]:
a=torch.rand(3,3)

In [28]:
a

tensor([[0.0497, 0.2587, 0.5783],
        [0.7159, 0.1017, 0.8776],
        [0.0951, 0.0381, 0.0626]])

In [31]:
b=torch.tensor([[1],[2],[3]])
b

tensor([[1],
        [2],
        [3]])

In [32]:
a*b

tensor([[0.0497, 0.2587, 0.5783],
        [1.4317, 0.2034, 1.7551],
        [0.2852, 0.1143, 0.1877]])